spring:
  application:
    name: login
#  datasource:
#    url: jdbc:mysql://localhost:3306/stepbystep?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: study
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update   # 개발단계에서는 update, 운영에서는 validate 권장
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.74:3306/TRAVELMAKER_DB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: study
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: kr.soft.login.dto
  configuration:
    map-underscore-to-camel-case: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

jwt:
  secret: my-super-secret-key-12345678901234567890

openai:
  api-key: ${OPENAI_API_KEY}
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
